# Generated by clang -MMD
src/main.o: src/main.c include/config.h \
  include/utils.h

# Another target
src/config.o: src/config.c include/config.h

src/utils.o: src/utils.c \
  include/utils.h \
  include/config.h
